# Generated by Django 3.2.25 on 2024-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='interest2',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='interest3',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='interest4',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='interest5',
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest1',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
