# Generated by Django 3.2.25 on 2024-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20240427_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interest1',
            new_name='interest',
        ),
    ]
