# Generated by Django 3.2.25 on 2024-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_interest1_interest_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='achievement1',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='achievement2',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='achievement3',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='achievement4',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='achievement5',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='to_date',
            field=models.DateField(blank=True),
        ),
    ]
