# Generated by Django 3.2.25 on 2024-04-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20240427_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_experience',
            old_name='achievement1',
            new_name='achievement',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='achievement2',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='achievement3',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='achievement4',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='achievement5',
        ),
    ]
