# Generated by Django 3.2.25 on 2024-04-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_rename_qualifation_education_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
