# Generated by Django 3.2.25 on 2024-04-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_education_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_me',
            new_name='About',
        ),
    ]
