# Generated by Django 3.2.25 on 2024-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_rename_about_me_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
