# Generated by Django 3.2.25 on 2024-04-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_about_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_experience',
            name='achievement',
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(max_length=250)),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.work_experience')),
            ],
        ),
    ]
