# Generated by Django 3.2.25 on 2024-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_auto_20240505_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='achievement1',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
