# Generated by Django 3.2.25 on 2024-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_alter_work_experience_achievement1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='achievement1',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
