# Generated by Django 3.2.25 on 2024-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_auto_20240505_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='achievement1',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='achievement2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='achievement3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
