# Generated by Django 3.2.25 on 2024-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20240505_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
