# Generated by Django 3.2.25 on 2024-05-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_alter_work_experience_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
