# Generated by Django 3.2.25 on 2024-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_alter_education_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='achievement2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='achievement3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
