# Generated by Django 3.2.25 on 2024-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20240516_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='achievement4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='achievement5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
