# Generated by Django 3.2.25 on 2024-05-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20240429_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='web_address',
            field=models.URLField(max_length=500),
        ),
    ]
