# Generated by Django 3.2.25 on 2024-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_web_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='git_address',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
