# Generated by Django 3.2.25 on 2024-05-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_git_address_portfolio_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='github',
        ),
    ]
