# Generated by Django 3.2.25 on 2024-05-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_portfolio_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='git_address',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
