# Generated by Django 3.2.25 on 2024-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_git_address_portfolio_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
